### ISSUE TITLE
How to Use it?

### ISSUE THREAD

**Issue by dikynugraha1111** [andrinur13/express-mongo-api#1]

**Comment by andrinur13** [comment]
1. Clone this repo to your machine
2. Run in the root directory project with command **_yarn install_** or **_npm install_**
3. Make sure you have installed mongo DB server and run it. Mongo DB is feel free to install natively or with Docker
4. Create your .env file with KEY: **JWT_KEY** and drop your key (feel free) to .env files. ENV files can be used by sevice JWT in authentication in this project

**Comment by dikynugraha1111** [comment]
does it have an API or a similar service to use it into front end?
I have read from your repository desc before, where the repo is desciribe to created a backend of musikipedia/ spotify clone. is that true?
if you have a more experience about back end,specially to created some service's. Please contact me, i have a job for you.
